### ISSUE TITLE
Importing amitran O/D Matrices

### ISSUE THREAD

**Issue by nudtdyk** [eclipse-sumo/sumo#13996]
Add your issue description here.

As we have seen, amitran O/D Matrices are of the following form:
![image](https://github.com/eclipse-sumo/sumo/assets/120693511/0b987dc8-0803-4dfa-8c77-eaf3bb6bee9a)

*If possible, upload an example that shows your problem.*
I wondered if I could add a few more time slices, but when I added other time slices I found that od2trips doesn't run in full
![image](https://github.com/eclipse-sumo/sumo/assets/120693511/7d8cb025-3205-41ee-8bef-bd87c666fc52)
![image](https://github.com/eclipse-sumo/sumo/assets/120693511/afacbcc1-1f78-4024-98f8-613d5a4ee549)

**SUMO-version:**
SUMO v1_18_0+1122-6a98504d485
**operating system:**
Windows 10

**Comment by m-kro** [comment]
What do you mean by " doesn't run in full"?

**Comment by nudtdyk** [comment]
I am very sorry that I did not explain myself clearly. I mean that the program ends when it reaches 82.02 seconds and doesn't load the time slice completely.

**Comment by m-kro** [comment]
Then please share your data to replicate the problem.

**Comment by m-kro** [comment]
You didn't provide the referenced TAZ file.

**Comment by nudtdyk** [comment]
Sorry again, and the corresponding supplementary document is below:
[osm_taz.zip](https://github.com/eclipse-sumo/sumo/files/13189333/osm_taz.zip)

**Comment by m-kro** [comment]
You'll have to provide the interval times in milliseconds. I admit this was very much hidden in our documentation and has been corrected.

**Comment by nudtdyk** [comment]
I'm very sorry for bothering you again. I'd like to know how to solve this problem. I'm still not very clear about it. Thank you.

**Comment by m-kro** [comment]
Just add three "0" to every time value (`duration` and `startTime` attributes) to convert the value from s to ms.

**Comment by nudtdyk** [comment]
Thanks very much!
