### ISSUE TITLE
Saving of Stops causes problems

### ISSUE THREAD

**Issue by luifire** [eclipse-sumo/sumo#14793]
I can save and load my example in a setting without stops. 
I am using basic `traci.simulation.saveState` and `traci.simulation.loadState`.

When I add stops (which I do a lot), I get the following issue

`traci.exceptions.TraCIException: Loading state from '###' failed, check whether SUMO versions match. stop for vehicle '0' on lane 'Insert' is not downstream the current route.`

On checking the save file, I find that all past stops are stored

```
<stop lane="Insert" startPos="28.90" endPos="29.00" duration="00:00:00" started="00:00:14" ended="00:00:15"/>
<stop lane="A1" startPos="8.90" endPos="9.00" duration="00:00:00" started="00:01:03" ended="00:01:04"/>
<stop lane="A2" startPos="8.90" endPos="9.00" duration="00:00:00" started="00:01:27" ended="00:01:28"/>
<stop lane="A1" startPos="8.90" endPos="9.00" duration="00:00:00" started="00:02:00" ended="00:02:01"/>
<stop lane="A2 startPos="8.90" endPos="9.00" duration="00:00:00" started="00:02:31" ended="00:02:32"/>
<stop lane="A1" startPos="8.90" endPos="9.00" duration="00:00:00" started="00:02:57" ended="00:03:01"/>
...
<stop lane="A2" startPos="8.90" endPos="9.00"/>
```

When I remove all stops that have passed, I find that the remaining stop is missing a duration.
`<stop lane="A2" startPos="8.90" endPos="9.00"/>`

It still can't be loaded and the error is
`traci.exceptions.FatalTraCIError: Connection closed by SUMO.`

When I add a duration the error remains.
`<stop lane="A2" startPos="8.90" endPos="9.00" duration="01:00:00"/>`

I would really appreciate suggestions or workarounds.
Thanks in advance.

---------------------------

I just realized, that when I save and load every couple of steps, my vehicles will respawn with some offset (they should be on the pink line), in which case nothing works anymore.
![image](https://github.com/eclipse-sumo/sumo/assets/53562633/1fd03098-e2ef-4e79-aa9e-654e7e30cd31)
Since it seems that saving and loading is currently in bad state, I will probably look for a different solution.

Anyway, I will leave this issue just so you are aware of it.
Thanks for Sumo and best

**SUMO-version:**
1.19.
Traci Version: (21, 'SUMO 1.19.0')

**operating system:**
Win 10

**Comment by m-kro** [comment]
Would you mind providing us an example scenario such that we can reproduce it hopefully quickly?

**Comment by luifire** [comment]
I understand that this would help you. Unfortunately I can't give you my project and since I am not that quick with Sumo, it will probably take me like 2 hrs to create the setup for which I don't have the time. 
So thank you for your consideration, and I am sorry for the circumstances.

The setup I would build is:
- Two connected streets A, B

(From here use traci)
- Adding a vehicle on A
- Setting the route from A to B
- Add a stop at the end of A
- After A passed the intersection to B, add a stop at the end of B.
- save and reload

**Comment by m-kro** [comment]
@luifire Is _Insert_ a placeholder for the real lane ID or not? Lane IDs should follow the scheme _edgeID_LaneIndex_. Did you edit your net file manually? Please see our [FAQ item](https://sumo.dlr.de/docs/FAQ.html#i_made_changes_to_the_netxml-file_but_it_did_not_work_as_expected_why) on that.

**Comment by luifire** [comment]
I edited it to be more readable on github.
In the safe file it is "BL.Insert._0".

**Comment by m-kro** [comment]
I cannot reproduce it given your previous notes. Your state excerpt suggests the vehicle runs in a circle (A1 > A2 > A1). Is this correct? Maybe you could at least provide us with a TraCI log file (see [doc](https://sumo.dlr.de/docs/TraCI/Interfacing_TraCI_from_Python.html#generating_a_log_of_all_traci_commands)), so that we get the right order and the exact function parameters.

**Comment by luifire** [comment]
Your engagement got me trying to entangle the project to get you a running example. However, after a good while, issues kept on appearing and I stopped doing this.
If you want to, we could arrange a brief meeting, trying to reproduce the issue. You can PM me here https://www.linkedin.com/in/luibrand/



Btw: on a test where I save and load after each step, it works until the first vehicle reaches a stop point

One step before the first stop:
![image](https://github.com/eclipse-sumo/sumo/assets/53562633/00a1f350-60e9-4bd3-9918-e69823983bd2)

One step after that
![image](https://github.com/eclipse-sumo/sumo/assets/53562633/33a9e95d-7eaa-48fb-82f7-1c3730ecfd8d)

**Comment by luifire** [comment]
I forgot to mention: when I start with `f'--traceFile={BASE_DIR}trace.file'` I get 

`C:\Program Files (x86)\Eclipse\Sumo\tools\traci\main.py:154: UserWarning: Could not connect to TraCI server using port 52077 (TraCI server already finished). Retrying with different port.
  warnings.warn(("Could not connect to TraCI server using port %s (%s)." +`
`C:\Program Files (x86)\Eclipse\Sumo\tools\traci\main.py:154: UserWarning: Could not connect to TraCI server using port 52080 (TraCI server already finished). Retrying with different port.
  warnings.warn(("Could not connect to TraCI server using port %s (%s)." +`
...

**Comment by luifire** [comment]
Forgot the traces
This one causes the jump (I save and reload after every step)
[jump when reloading traces.log](https://github.com/eclipse-sumo/sumo/files/15186534/jump.when.reloading.traces.log)

This one causes the complete breakdown. I save and reload after 100 steps
[error when loading traces.log](https://github.com/eclipse-sumo/sumo/files/15186546/error.when.loading.traces.log)

**Comment by m-kro** [comment]
[luifire.zip](https://github.com/eclipse-sumo/sumo/files/15235957/luifire.zip)
There was nothing out of the ordinary in the log files. I have prepared a small example for the save and reload case you can adapt to your case and see at which point it goes wrong.

**Comment by luifire** [comment]
Thank you very much.
Using your minimum setup, I was able to reproduce both issues.
[luifire.zip](https://github.com/eclipse-sumo/sumo/files/15402538/luifire.zip)

I created runnerSaveLoad_bug1.py and runnerSaveLoad_bug2.py with the distinct issues.

**Bug 1** seems pretty straight forward:
I was using `traci.vehicle.setStop(vehID, "insert", pos=50, duration=sys.float_info.max)`, and duration seems to be a float16, but `sys.float_info.max` is float64. 
It is properly handled by `insertStop` and `setStopParameter`.


**Bug 2** is about wrong stops that have passed. I would recommend to compare traciState_44.xml and traciState_45.xml (they are produced by the script).

**Comment by m-kro** [comment]
@luifire Thank you for providing the example files. The mentioned problems have been fixed:

- The first problem has been addressed in #14904 . Using the development version of SUMO you can now set `sys.float_info.max` as stop duration. 
- The second one has been addressed in #14918 . Keeping passed stops in the state file conflicts with the updated route, as the stop cannot be mapped to a route edge. So now we drop those which do not match anymore. 

From tomorrow on, the patches will be both included in the [development binaries](https://sumo.dlr.de/docs/Downloads.php#sumo_-_latest_development_version). If you can't wait, you can compile it yourself from Github source.

**Comment by luifire** [comment]
@m-kro @namdre Thank you very much.

 This #14918 seems to be fixed.

#14904 still appears.
![image](https://github.com/eclipse-sumo/sumo/assets/53562633/4137425b-cf70-4ed6-9725-e9fe77732f54)
![image](https://github.com/eclipse-sumo/sumo/assets/53562633/f844cd3e-3e14-467d-8a84-e3ba33ac33f1)
(The sumo version matches todays nightly build: v1_20_0+0229-9bb6e39c011)

-----------
I am not sure if I had to install the latest traci version as well. So I tried both.

Side note, when I ran `pip install -f https://sumo.dlr.de/daily/wheels/ eclipse-sumo
`, I get 
![image](https://github.com/eclipse-sumo/sumo/assets/53562633/8c6024a9-513e-489e-9bb1-9dbd0c9c4703)

I downloaded and installed the latest whl files directly.

**Comment by m-kro** [comment]
On my side, all the following stop durations you supplied work (no overflow with subsequent strange results like offroad parking):
 ```
[
np.finfo(np.float32).max, # evaluates to 3.4028235e+38
sys.float_info.max, # evaluates to 1.7976931348623157e+308
]
```

**Comment by luifire** [comment]
I am not completely sure, that I am using the correct version from last night.
Here is an image of every version that I could find

![image](https://github.com/eclipse-sumo/sumo/assets/53562633/342679b1-e660-4b26-8b8e-b2b8dad9b59b)


What I am also curious about, is that this is considered an invalide double: [`INVALID_DOUBLE_VALUE = -1073741824.0`](https://github.com/eclipse-sumo/sumo/blob/d288101929872298a3c004475e9e3e90f03af22b/tools/traci/constants.py#L503)
Used in [setStop](https://github.com/eclipse-sumo/sumo/blob/d288101929872298a3c004475e9e3e90f03af22b/tools/traci/_vehicle.py#L1012).

**Comment by namdre** [comment]
the INVALID_DOUBLE is not technically invalid. It's just a "magic" value to signal undefined data.

**Comment by luifire** [comment]
🥳 This works.
Thank you, and again thanks for SUMO.
